export const en = {
  newSearch: "New Search",
  favoriteAlertTitle: "Alert ⚠️",
  favoriteAlertMessage: "you will DELETE all Favorites",
  cancelDeleteTitle: "Done ✅",
  cancelDeleteMessage: "Undo Delete process",
  searchErrorTitle: "Not Found",
  searchErrorMessage:
    "No Sound Found by this name check your search term and try again",
  searchEmptyTitle: "No Query",
  searchEmptyMessage: "Type something to search for",
  errorTitle: "Error",
  errorMessage: "No Song File Found",
  home: "Home",
  favorites: "Favorites",
  categories: "Categories",
  search: "Search",
  emptyFavorite: "You have no favorites yet",
  searchInput: "type your search term",
  searchButton: "Search",
};
